# ============== Job Status ==============
JOB_STATUS_OPEN = "OPEN"
JOB_STATUS_PAUSED = "PAUSED"
JOB_STATUS_CLOSED = "CLOSED"
VALID_JOB_STATUSES = {JOB_STATUS_OPEN, JOB_STATUS_PAUSED, JOB_STATUS_CLOSED}

# ============== Candidate Status ==============
STATUS_IMPORTED = "IMPORTED"
STATUS_RESUME_PENDING = "RESUME_PENDING"
STATUS_RESUME_PASSED = "RESUME_PASSED"
STATUS_RESUME_REJECTED = "RESUME_REJECTED"
STATUS_FIRST_INTERVIEW_PENDING = "FIRST_INTERVIEW_PENDING"
STATUS_FIRST_INTERVIEW_PASSED = "FIRST_INTERVIEW_PASSED"
STATUS_FIRST_INTERVIEW_REJECTED = "FIRST_INTERVIEW_REJECTED"
STATUS_SECOND_INTERVIEW_PENDING = "SECOND_INTERVIEW_PENDING"
STATUS_SECOND_INTERVIEW_PASSED = "SECOND_INTERVIEW_PASSED"
STATUS_SECOND_INTERVIEW_REJECTED = "SECOND_INTERVIEW_REJECTED"
STATUS_HIRED = "HIRED"
STATUS_ABANDONED = "ABANDONED"
STATUS_TALENT_POOL = "TALENT_POOL"

VALID_CANDIDATE_STATUSES = {
    STATUS_IMPORTED,
    STATUS_RESUME_PENDING,
    STATUS_RESUME_PASSED,
    STATUS_RESUME_REJECTED,
    STATUS_FIRST_INTERVIEW_PENDING,
    STATUS_FIRST_INTERVIEW_PASSED,
    STATUS_FIRST_INTERVIEW_REJECTED,
    STATUS_SECOND_INTERVIEW_PENDING,
    STATUS_SECOND_INTERVIEW_PASSED,
    STATUS_SECOND_INTERVIEW_REJECTED,
    STATUS_HIRED,
    STATUS_ABANDONED,
    STATUS_TALENT_POOL,
}

# ============== Stage Type ==============
STAGE_RESUME_SCREENING = "RESUME_SCREENING"
STAGE_FIRST_INTERVIEW = "FIRST_INTERVIEW"
STAGE_SECOND_INTERVIEW = "SECOND_INTERVIEW"
VALID_STAGE_TYPES = {STAGE_RESUME_SCREENING, STAGE_FIRST_INTERVIEW, STAGE_SECOND_INTERVIEW}

# ============== Report Status ==============
REPORT_STATUS_PROCESSING = "PROCESSING"
REPORT_STATUS_SUCCESS = "SUCCESS"
REPORT_STATUS_FAILED = "FAILED"
VALID_REPORT_STATUSES = {REPORT_STATUS_PROCESSING, REPORT_STATUS_SUCCESS, REPORT_STATUS_FAILED}

# ============== Round Type ==============
ROUND_TYPE_FIRST = "FIRST"
ROUND_TYPE_SECOND = "SECOND"
VALID_ROUND_TYPES = {ROUND_TYPE_FIRST, ROUND_TYPE_SECOND}

# ============== Status Machine ==============
ALLOWED_STATUS_TRANSITIONS = {
    STATUS_IMPORTED: {STATUS_RESUME_PENDING, STATUS_ABANDONED},
    STATUS_RESUME_PENDING: {STATUS_RESUME_PASSED, STATUS_RESUME_REJECTED, STATUS_TALENT_POOL, STATUS_ABANDONED},
    STATUS_RESUME_PASSED: {STATUS_FIRST_INTERVIEW_PENDING, STATUS_TALENT_POOL, STATUS_ABANDONED},
    STATUS_FIRST_INTERVIEW_PENDING: {STATUS_FIRST_INTERVIEW_PASSED, STATUS_FIRST_INTERVIEW_REJECTED, STATUS_TALENT_POOL, STATUS_ABANDONED},
    STATUS_FIRST_INTERVIEW_PASSED: {STATUS_SECOND_INTERVIEW_PENDING, STATUS_TALENT_POOL, STATUS_ABANDONED},
    STATUS_SECOND_INTERVIEW_PENDING: {STATUS_SECOND_INTERVIEW_PASSED, STATUS_SECOND_INTERVIEW_REJECTED, STATUS_TALENT_POOL, STATUS_ABANDONED},
    STATUS_SECOND_INTERVIEW_PASSED: {STATUS_HIRED, STATUS_TALENT_POOL, STATUS_ABANDONED},
}

# ============== AI Report Validations ==============
RESUME_SUGGESTIONS = {"建议约初试", "建议淘汰", "人才库储备"}
FIRST_INTERVIEW_SUGGESTIONS = {"建议进入复试", "建议淘汰", "人才库储备"}
SECOND_INTERVIEW_SUGGESTIONS = {"录用", "人才库储备", "淘汰"}
VALID_RISK_LEVELS = {"低", "中", "高"}

STAGE_SUGGESTIONS = {
    STAGE_RESUME_SCREENING: RESUME_SUGGESTIONS,
    STAGE_FIRST_INTERVIEW: FIRST_INTERVIEW_SUGGESTIONS,
    STAGE_SECOND_INTERVIEW: SECOND_INTERVIEW_SUGGESTIONS,
}
