# ============== Job Status ==============
JOB_STATUS_OPEN = "OPEN"
JOB_STATUS_PAUSED = "PAUSED"
JOB_STATUS_CLOSED = "CLOSED"
JOB_STATUS_ARCHIVED = "ARCHIVED"
VALID_JOB_STATUSES = {JOB_STATUS_OPEN, JOB_STATUS_PAUSED, JOB_STATUS_CLOSED, JOB_STATUS_ARCHIVED}

# ============== Job Type（岗位类型） ==============
JOB_TYPE_SALES = "销售业务类"
JOB_TYPE_ECOMMERCE = "电商运营类"
JOB_TYPE_CUSTOMER_SERVICE = "客服售后类"
JOB_TYPE_ADMIN_HR = "行政人事类"
JOB_TYPE_FINANCE = "财务出纳类"
JOB_TYPE_WAREHOUSE = "仓储物流类"
JOB_TYPE_INSTALLATION = "安装维修类"
JOB_TYPE_ENTRY_LEVEL_MGMT = "基层管理类"
JOB_TYPE_GENERAL = "通用岗位类"

VALID_JOB_TYPES = {
    JOB_TYPE_SALES,
    JOB_TYPE_ECOMMERCE,
    JOB_TYPE_CUSTOMER_SERVICE,
    JOB_TYPE_ADMIN_HR,
    JOB_TYPE_FINANCE,
    JOB_TYPE_WAREHOUSE,
    JOB_TYPE_INSTALLATION,
    JOB_TYPE_ENTRY_LEVEL_MGMT,
    JOB_TYPE_GENERAL,
}

# 岗位类型评估重点
JOB_TYPE_EVALUATION_FOCUS = {
    JOB_TYPE_SALES: [
        "销售经验", "客户开发能力", "沟通谈判能力", "抗压能力",
        "业绩意识", "客户维护能力", "稳定性"
    ],
    JOB_TYPE_CUSTOMER_SERVICE: [
        "沟通表达能力", "情绪稳定性", "服务意识", "投诉处理能力",
        "平台工具使用经验", "耐心程度", "抗压能力"
    ],
    JOB_TYPE_ADMIN_HR: [
        "细心程度", "执行力", "沟通协调能力", "文档整理能力",
        "服务意识", "保密意识", "办公软件能力", "事务跟进能力", "稳定性"
    ],
    JOB_TYPE_FINANCE: [
        "财务基础", "数据准确性", "Excel能力", "票据处理经验",
        "原则性", "保密意识", "细心程度", "稳定性"
    ],
    JOB_TYPE_WAREHOUSE: [
        "吃苦耐劳", "责任心", "库存管理经验", "发货准确性",
        "异常处理能力", "服从安排", "稳定性"
    ],
    JOB_TYPE_GENERAL: [
        "学习能力", "沟通能力", "责任心", "团队协作", "稳定性"
    ],
}

# ============== Candidate Status ==============
STATUS_IMPORTED = "IMPORTED"
STATUS_RESUME_IMPORTED = "RESUME_IMPORTED"
STATUS_RESUME_PARSING = "RESUME_PARSING"
STATUS_RESUME_PARSE_FAILED = "RESUME_PARSE_FAILED"
STATUS_RESUME_PENDING = "RESUME_PENDING"
STATUS_RESUME_SCREENING = "RESUME_SCREENING"
STATUS_RESUME_SCREENING_DONE = "RESUME_SCREENING_DONE"
STATUS_RESUME_PASSED = "RESUME_PASSED"
STATUS_RESUME_TBD = "RESUME_TBD"
STATUS_RESUME_REJECTED = "RESUME_REJECTED"
STATUS_INTERVIEW_WAITING = "INTERVIEW_WAITING"
STATUS_INTERVIEW_SCHEDULED = "INTERVIEW_SCHEDULED"
STATUS_INTERVIEW_DECISION_PENDING = "INTERVIEW_DECISION_PENDING"
STATUS_FINAL_PASSED = "FINAL_PASSED"
STATUS_REJECTED = "REJECTED"
STATUS_ON_HOLD = "ON_HOLD"
STATUS_FIRST_INTERVIEW_PENDING = "FIRST_INTERVIEW_PENDING"
STATUS_FIRST_INTERVIEW_IN_PROGRESS = "FIRST_INTERVIEW_IN_PROGRESS"
STATUS_FIRST_INTERVIEW_PASSED = "FIRST_INTERVIEW_PASSED"
STATUS_FIRST_INTERVIEW_REJECTED = "FIRST_INTERVIEW_REJECTED"
STATUS_SECOND_INTERVIEW_PENDING = "SECOND_INTERVIEW_PENDING"
STATUS_SECOND_INTERVIEW_IN_PROGRESS = "SECOND_INTERVIEW_IN_PROGRESS"
STATUS_SECOND_INTERVIEW_PASSED = "SECOND_INTERVIEW_PASSED"
STATUS_SECOND_INTERVIEW_REJECTED = "SECOND_INTERVIEW_REJECTED"
STATUS_HIRED = "HIRED"
STATUS_ONBOARDED = "ONBOARDED"
STATUS_OFFER_ABANDONED = "OFFER_ABANDONED"
STATUS_ABANDONED = "ABANDONED"
STATUS_TALENT_POOL = "TALENT_POOL"

VALID_CANDIDATE_STATUSES = {
    STATUS_IMPORTED,
    STATUS_RESUME_IMPORTED,
    STATUS_RESUME_PARSING,
    STATUS_RESUME_PARSE_FAILED,
    STATUS_RESUME_PENDING,
    STATUS_RESUME_SCREENING,
    STATUS_RESUME_SCREENING_DONE,
    STATUS_RESUME_PASSED,
    STATUS_RESUME_TBD,
    STATUS_RESUME_REJECTED,
    STATUS_INTERVIEW_WAITING,
    STATUS_INTERVIEW_SCHEDULED,
    STATUS_INTERVIEW_DECISION_PENDING,
    STATUS_FINAL_PASSED,
    STATUS_REJECTED,
    STATUS_ON_HOLD,
    STATUS_FIRST_INTERVIEW_PENDING,
    STATUS_FIRST_INTERVIEW_IN_PROGRESS,
    STATUS_FIRST_INTERVIEW_PASSED,
    STATUS_FIRST_INTERVIEW_REJECTED,
    STATUS_SECOND_INTERVIEW_PENDING,
    STATUS_SECOND_INTERVIEW_IN_PROGRESS,
    STATUS_SECOND_INTERVIEW_PASSED,
    STATUS_SECOND_INTERVIEW_REJECTED,
    STATUS_HIRED,
    STATUS_ONBOARDED,
    STATUS_OFFER_ABANDONED,
    STATUS_ABANDONED,
    STATUS_TALENT_POOL,
}

CANDIDATE_STATUS_LABELS = {
    STATUS_IMPORTED: "简历已导入",
    STATUS_RESUME_IMPORTED: "简历已导入",
    STATUS_RESUME_PARSING: "简历解析中",
    STATUS_RESUME_PARSE_FAILED: "简历解析失败",
    STATUS_RESUME_PENDING: "待初筛",
    STATUS_RESUME_SCREENING: "初筛中",
    STATUS_RESUME_SCREENING_DONE: "初筛完成",
    STATUS_RESUME_PASSED: "推荐面试",
    STATUS_RESUME_TBD: "待定",
    STATUS_RESUME_REJECTED: "初筛淘汰",
    STATUS_INTERVIEW_WAITING: "待安排面试",
    STATUS_INTERVIEW_SCHEDULED: "面试待进行",
    STATUS_INTERVIEW_DECISION_PENDING: "面试完成待决策",
    STATUS_FINAL_PASSED: "通过并结束",
    STATUS_REJECTED: "已淘汰",
    STATUS_ON_HOLD: "暂定",
    STATUS_FIRST_INTERVIEW_PENDING: "已约面试",
    STATUS_FIRST_INTERVIEW_IN_PROGRESS: "初试中",
    STATUS_FIRST_INTERVIEW_PASSED: "初试通过",
    STATUS_FIRST_INTERVIEW_REJECTED: "初试淘汰",
    STATUS_SECOND_INTERVIEW_PENDING: "复试中",
    STATUS_SECOND_INTERVIEW_IN_PROGRESS: "复试中",
    STATUS_SECOND_INTERVIEW_PASSED: "复试通过",
    STATUS_SECOND_INTERVIEW_REJECTED: "复试淘汰",
    STATUS_HIRED: "已录用",
    STATUS_ONBOARDED: "已入职",
    STATUS_OFFER_ABANDONED: "放弃入职",
    STATUS_ABANDONED: "放弃入职",
    STATUS_TALENT_POOL: "待定",
}

# ============== Stage Type ==============
STAGE_RESUME_SCREENING = "RESUME_SCREENING"
STAGE_FIRST_INTERVIEW = "FIRST_INTERVIEW"
STAGE_SECOND_INTERVIEW = "SECOND_INTERVIEW"
STAGE_CANDIDATE_EVALUATION = "CANDIDATE_EVALUATION"
STAGE_INTERVIEW_QUESTIONS = "INTERVIEW_QUESTIONS"
VALID_STAGE_TYPES = {
    STAGE_RESUME_SCREENING,
    STAGE_FIRST_INTERVIEW,
    STAGE_SECOND_INTERVIEW,
    STAGE_CANDIDATE_EVALUATION,
    STAGE_INTERVIEW_QUESTIONS,
}

# ============== Report Status ==============
REPORT_STATUS_PROCESSING = "PROCESSING"
REPORT_STATUS_SUCCESS = "SUCCESS"
REPORT_STATUS_FAILED = "FAILED"
VALID_REPORT_STATUSES = {REPORT_STATUS_PROCESSING, REPORT_STATUS_SUCCESS, REPORT_STATUS_FAILED}

# ============== Report Generate Type ==============
REPORT_GENERATE_AUTO = "AUTO"
REPORT_GENERATE_MANUAL_RERUN = "MANUAL_RERUN"
VALID_REPORT_GENERATE_TYPES = {REPORT_GENERATE_AUTO, REPORT_GENERATE_MANUAL_RERUN}

# ============== Round Type ==============
ROUND_TYPE_FIRST = "FIRST"
ROUND_TYPE_SECOND = "SECOND"
VALID_ROUND_TYPES = {ROUND_TYPE_FIRST, ROUND_TYPE_SECOND}

# ============== Interview Question Round Type ==============
QUESTION_ROUND_TYPE_FIRST = "FIRST_INTERVIEW"
QUESTION_ROUND_TYPE_SECOND = "SECOND_INTERVIEW"
QUESTION_ROUND_TYPE_FINAL = "FINAL_INTERVIEW"
QUESTION_ROUND_TYPE_HR = "HR_INTERVIEW"
QUESTION_ROUND_TYPE_OTHER = "OTHER"
VALID_INTERVIEW_QUESTION_ROUND_TYPES = {
    QUESTION_ROUND_TYPE_FIRST,
    QUESTION_ROUND_TYPE_SECOND,
    QUESTION_ROUND_TYPE_FINAL,
    QUESTION_ROUND_TYPE_HR,
    QUESTION_ROUND_TYPE_OTHER,
}
INTERVIEW_QUESTION_ROUND_TYPE_LABELS = {
    QUESTION_ROUND_TYPE_FIRST: "初试问题",
    QUESTION_ROUND_TYPE_SECOND: "复试问题",
    QUESTION_ROUND_TYPE_FINAL: "终面问题",
    QUESTION_ROUND_TYPE_HR: "HR 面问题",
    QUESTION_ROUND_TYPE_OTHER: "其他问题",
}

# ============== Open Interview Round ==============
INTERVIEW_ROUND_STATUS_SCHEDULED = "SCHEDULED"
INTERVIEW_ROUND_STATUS_COMPLETED = "COMPLETED"
INTERVIEW_ROUND_STATUS_CANCELED = "CANCELED"
VALID_INTERVIEW_ROUND_STATUSES = {
    INTERVIEW_ROUND_STATUS_SCHEDULED,
    INTERVIEW_ROUND_STATUS_COMPLETED,
    INTERVIEW_ROUND_STATUS_CANCELED,
}

INTERVIEW_DECISION_PASS_END = "通过并结束"
INTERVIEW_DECISION_NEXT = "进入下一轮"
INTERVIEW_DECISION_HOLD = "暂定"
INTERVIEW_DECISION_REJECT = "淘汰"
VALID_INTERVIEW_DECISIONS = {
    INTERVIEW_DECISION_PASS_END,
    INTERVIEW_DECISION_NEXT,
    INTERVIEW_DECISION_HOLD,
    INTERVIEW_DECISION_REJECT,
}

# ============== Status Machine ==============
ALLOWED_STATUS_TRANSITIONS = {
    STATUS_IMPORTED: {STATUS_RESUME_PENDING, STATUS_RESUME_PARSING, STATUS_ABANDONED},
    STATUS_RESUME_IMPORTED: {STATUS_RESUME_PARSING, STATUS_RESUME_PARSE_FAILED, STATUS_RESUME_PENDING, STATUS_ABANDONED},
    STATUS_RESUME_PARSING: {STATUS_RESUME_PARSE_FAILED, STATUS_RESUME_PENDING, STATUS_ABANDONED},
    STATUS_RESUME_PARSE_FAILED: {STATUS_RESUME_PARSING, STATUS_ABANDONED},
    STATUS_RESUME_PENDING: {STATUS_RESUME_SCREENING, STATUS_RESUME_PASSED, STATUS_RESUME_REJECTED, STATUS_RESUME_TBD, STATUS_INTERVIEW_WAITING, STATUS_TALENT_POOL, STATUS_ABANDONED},
    STATUS_RESUME_SCREENING: {STATUS_RESUME_SCREENING_DONE, STATUS_RESUME_PASSED, STATUS_RESUME_REJECTED, STATUS_RESUME_TBD, STATUS_INTERVIEW_WAITING, STATUS_ABANDONED},
    STATUS_RESUME_SCREENING_DONE: {STATUS_RESUME_PASSED, STATUS_RESUME_REJECTED, STATUS_RESUME_TBD, STATUS_INTERVIEW_WAITING, STATUS_ABANDONED},
    STATUS_RESUME_PASSED: {STATUS_INTERVIEW_WAITING, STATUS_FIRST_INTERVIEW_PENDING, STATUS_TALENT_POOL, STATUS_ABANDONED},
    STATUS_RESUME_TBD: {STATUS_RESUME_PASSED, STATUS_RESUME_REJECTED, STATUS_INTERVIEW_WAITING, STATUS_FIRST_INTERVIEW_PENDING, STATUS_ABANDONED},
    STATUS_INTERVIEW_WAITING: {STATUS_INTERVIEW_SCHEDULED, STATUS_ON_HOLD, STATUS_REJECTED, STATUS_ABANDONED},
    STATUS_INTERVIEW_SCHEDULED: {STATUS_INTERVIEW_DECISION_PENDING, STATUS_INTERVIEW_WAITING, STATUS_ON_HOLD, STATUS_REJECTED, STATUS_ABANDONED},
    STATUS_INTERVIEW_DECISION_PENDING: {STATUS_FINAL_PASSED, STATUS_INTERVIEW_SCHEDULED, STATUS_ON_HOLD, STATUS_REJECTED, STATUS_ABANDONED},
    STATUS_ON_HOLD: {STATUS_INTERVIEW_WAITING, STATUS_INTERVIEW_SCHEDULED, STATUS_REJECTED, STATUS_ABANDONED},
    STATUS_REJECTED: {STATUS_INTERVIEW_WAITING},
    STATUS_FINAL_PASSED: {STATUS_INTERVIEW_WAITING},
    STATUS_FIRST_INTERVIEW_PENDING: {STATUS_FIRST_INTERVIEW_IN_PROGRESS, STATUS_FIRST_INTERVIEW_PASSED, STATUS_FIRST_INTERVIEW_REJECTED, STATUS_TALENT_POOL, STATUS_ABANDONED},
    STATUS_FIRST_INTERVIEW_IN_PROGRESS: {STATUS_FIRST_INTERVIEW_PASSED, STATUS_FIRST_INTERVIEW_REJECTED, STATUS_TALENT_POOL, STATUS_ABANDONED},
    STATUS_FIRST_INTERVIEW_PASSED: {STATUS_SECOND_INTERVIEW_PENDING, STATUS_TALENT_POOL, STATUS_ABANDONED},
    STATUS_SECOND_INTERVIEW_PENDING: {STATUS_SECOND_INTERVIEW_IN_PROGRESS, STATUS_SECOND_INTERVIEW_PASSED, STATUS_SECOND_INTERVIEW_REJECTED, STATUS_TALENT_POOL, STATUS_ABANDONED},
    STATUS_SECOND_INTERVIEW_IN_PROGRESS: {STATUS_SECOND_INTERVIEW_PASSED, STATUS_SECOND_INTERVIEW_REJECTED, STATUS_TALENT_POOL, STATUS_ABANDONED},
    STATUS_SECOND_INTERVIEW_PASSED: {STATUS_HIRED, STATUS_TALENT_POOL, STATUS_ABANDONED},
    STATUS_HIRED: {STATUS_ONBOARDED, STATUS_OFFER_ABANDONED},
}

# ============== Screening Task ==============
SCREENING_TASK_DRAFT = "DRAFT"
SCREENING_TASK_READY = "READY"
SCREENING_TASK_SCREENING = "SCREENING"
SCREENING_TASK_COMPLETED = "COMPLETED"
SCREENING_TASK_FAILED = "FAILED"
VALID_SCREENING_TASK_STATUSES = {
    SCREENING_TASK_DRAFT,
    SCREENING_TASK_READY,
    SCREENING_TASK_SCREENING,
    SCREENING_TASK_COMPLETED,
    SCREENING_TASK_FAILED,
}

RESUME_FILE_PENDING = "PENDING"
RESUME_FILE_UPLOADING = "UPLOADING"
RESUME_FILE_PARSING = "PARSING"
RESUME_FILE_SCREENING = "SCREENING"
RESUME_FILE_COMPLETED = "COMPLETED"
RESUME_FILE_FAILED = "FAILED"
RESUME_REUSE_SOURCE_FILE_HASH = "FILE_HASH"
RESUME_REUSE_SOURCE_TEXT_HASH = "TEXT_HASH"
RESUME_REUSE_SOURCE_IDENTITY = "IDENTITY"
VALID_RESUME_FILE_STATUSES = {
    RESUME_FILE_PENDING,
    RESUME_FILE_UPLOADING,
    RESUME_FILE_PARSING,
    RESUME_FILE_SCREENING,
    RESUME_FILE_COMPLETED,
    RESUME_FILE_FAILED,
}

SCREENING_CONCLUSION_RECOMMENDED = "RECOMMENDED"
SCREENING_CONCLUSION_PENDING = "PENDING"
SCREENING_CONCLUSION_REJECTED = "REJECTED"
VALID_SCREENING_CONCLUSIONS = {
    SCREENING_CONCLUSION_RECOMMENDED,
    SCREENING_CONCLUSION_PENDING,
    SCREENING_CONCLUSION_REJECTED,
}

SCREENING_RESULT_STATUS_RECOMMENDED = "RECOMMENDED"
SCREENING_RESULT_STATUS_PENDING = "PENDING"
SCREENING_RESULT_STATUS_REJECTED = "REJECTED"
SCREENING_RESULT_STATUS_INTERVIEW = "INTERVIEW"
SCREENING_RESULT_SOURCE_AI = "AI"
SCREENING_RESULT_SOURCE_REUSED = "REUSED"
VALID_SCREENING_RESULT_STATUSES = {
    SCREENING_RESULT_STATUS_RECOMMENDED,
    SCREENING_RESULT_STATUS_PENDING,
    SCREENING_RESULT_STATUS_REJECTED,
    SCREENING_RESULT_STATUS_INTERVIEW,
}

SCREENING_CONCLUSION_LABELS = {
    SCREENING_CONCLUSION_RECOMMENDED: "推荐面试",
    SCREENING_CONCLUSION_PENDING: "待定",
    SCREENING_CONCLUSION_REJECTED: "不推荐",
}

# ============== Settings ==============
PROMPT_KEY_JD_PARSE = "JD_PARSE"
PROMPT_KEY_RESUME_PARSE = "RESUME_PARSE"
PROMPT_KEY_SCREENING_MATCH = "SCREENING_MATCH"
VALID_PROMPT_KEYS = {
    PROMPT_KEY_JD_PARSE,
    PROMPT_KEY_RESUME_PARSE,
    PROMPT_KEY_SCREENING_MATCH,
}

PROMPT_STATUS_DRAFT = "DRAFT"
PROMPT_STATUS_ACTIVE = "ACTIVE"
PROMPT_STATUS_ARCHIVED = "ARCHIVED"
VALID_PROMPT_STATUSES = {
    PROMPT_STATUS_DRAFT,
    PROMPT_STATUS_ACTIVE,
    PROMPT_STATUS_ARCHIVED,
}

# ============== AI Report Validations ==============
RESUME_SUGGESTIONS = {"建议约初试", "建议淘汰", "人才库储备"}
FIRST_INTERVIEW_SUGGESTIONS = {"建议进入复试", "建议淘汰", "人才库储备"}
SECOND_INTERVIEW_SUGGESTIONS = {"录用", "人才库储备", "淘汰"}
VALID_RISK_LEVELS = {"低", "中", "高"}

STAGE_SUGGESTIONS = {
    STAGE_RESUME_SCREENING: RESUME_SUGGESTIONS,
    STAGE_FIRST_INTERVIEW: FIRST_INTERVIEW_SUGGESTIONS,
    STAGE_SECOND_INTERVIEW: SECOND_INTERVIEW_SUGGESTIONS,
}
